### ISSUE TITLE
Inability to use previous search implementations

### ISSUE THREAD

**Issue by alexandermeyer** [ivelum/djangoql#10]
If a field isn't supported, or if certain search features have been implemented before, there should be a way to "escape" back to previous search functionality.

For example, fields like uuids aren't searchable in DjangoQL. While there are ways to make them searchable, it would be convenient to have an escape character, like a backslash, to disable DjangoQL for that search.

**Comment by stebunovd** [comment]
I guess you can achieve that with an override of `.get_search_results()` method, like this:

```python
@admin.register(Book)
class BookAdmin(DjangoQLSearchMixin, admin.ModelAdmin):
    # Search fields for built-in Django search
    search_fields = ('name', 'author__first_name', 'author__last_name')

    def get_search_results(self, request, queryset, search_term):
        if search_term.startswith('\\'):
            # Leading backslash switches to built-in Django search
            return admin.ModelAdmin.get_search_results(
                self,
                request,
                queryset,
                search_term[1:],  # cut leading backslash
            )
        # DjangoQL search
        return super().get_search_results(request, queryset, search_term)
```

Is that what you need?

**Comment by alexandermeyer** [comment]
Yes, exactly. I had to remove '_djangoql' from the search fields and then everything worked great. Thank you.

**Comment by stebunovd** [comment]
Great! So probably we could close it now
