### ISSUE TITLE
Bug in custom AdminSite

### ISSUE THREAD

**Issue by pandichef** [ivelum/djangoql#101]
I have multiple admin sites as described [here](https://books.agiliq.com/projects/django-admin-cookbook/en/latest/two_admin.html).

I'm getting `Reverse for 'djangoql_syntax_help' not found. 'djangoql_syntax_help' is not a valid view function or pattern name.`

It's happening at `<a href="{% url 'admin:djangoql_syntax_help' %}" class="djangoql-help">` in `error_message.html`.

I fixed it by creating a regular admin for now (which I only use to patch this error).

**Comment by stebunovd** [comment]
Hi @pandichef,

thank you for reporting this. I have never used multiple admin sites before, so not sure what would be the proper way to fix this. Do you have any ideas?

**Comment by pandichef** [comment]
Proper,  no.  I just created a regular admin for now to handle the exception.

Btw, as an aside, I couldn't get "suggest_options" to work in a schema used in a non-admin view.   It's not critical for my use case, but I wanted you to know.

Notwithstanding the above, super package!
