### ISSUE TITLE
Restrict fields

### ISSUE THREAD

**Issue by MrMarble** [ivelum/djangoql#120]
Thanks for the work on djangoql, is amazing!

I'm wondering if there's any way to restrict which fields can be used with djangoql, we have some internal fields in the Models that are not intended to be used by the user, and djangoql allows to filter with them, but the main problem are suggestions and the message when you try to use a field that is not available, all those internal fields appear on the list.

I tried with the `exclude` option ([docs](https://django-filter.readthedocs.io/en/stable/ref/filterset.html#disable-filter-fields-with-exclude)) but that does not seem to work

**Comment by stebunovd** [comment]
Hi @MrMarble,

I guess the problem might be that you're referring to the django-filter docs and not the [DjangoQL docs](https://github.com/ivelum/djangoql?tab=readme-ov-file#djangoql-schema). Please try the example from the official docs and it should work.


Thanks,

Denis

**Comment by MrMarble** [comment]
I'll close the issue since I managed to filter out fields with the DjangoQL Schema
