### ISSUE TITLE
Please provide the raw completion.js

### ISSUE THREAD

**Issue by roniemartinez** [ivelum/djangoql#122]
We are trying to customize the autocomplete widget but it seems that [`completion.js`](https://github.com/ivelum/djangoql/blob/master/djangoql/static/djangoql/js/completion.js) is an uglified version. The raw javascript is nowhere to be found in this repo.

**Comment by stebunovd** [comment]
hey @roniemartinez, the completion widget source code is available at https://github.com/ivelum/djangoql-completion

**Comment by roniemartinez** [comment]
Thanks 🙇
