### ISSUE TITLE
Use of verbose_name for filters

### ISSUE THREAD

**Issue by gthieleb** [ivelum/djangoql#14]
Is it possible to use verbose_name of a model attribute instead of the attribute itself?

E.g. 

     'Title ~ "war" and Author.Last-Name = "Tolstoy"'

**Comment by stebunovd** [comment]
It's not possible in the current version, and actually, I don't see an easy way how it could be implemented on parser level. The biggest problem is that verbose names are not guaranteed to be unique. Another problem is that verbose names can contain literally any characters, so some kind of characters escaping would be necessary, and it could be challenging to implement it in a clear and user-friendly way.

However I guess we might consider adding verbose names into completion widget, probably it could make it easier for users to understand what do those attribute names mean.

**Comment by gthieleb** [comment]
Thanks for your quick response. Perhaps the user only needs to have the possible attributes displayed. I will look at the approach with the widget code.
