### ISSUE TITLE
Getting rid of RuntimeWarning: DateTimeField received a naive datetime + is there something like TimeField?

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [ivelum/djangoql#15]
First of all thank you for this package, it saved me huge amount of time. To the point:

I had a test in which I was filtering with some datetime:

```python
self.client.get(
    '/users/user_1/meals/',
    {'filter': 'datetime_created < "2017-01-02 00:00:00"'},
    content_type='application/json',
)
```

When running `./manage.py test` (Django 1.11) I received such warnings:

`/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Meal.datetime_created received a naive datetime (2017-01-02 00:00:00) while time zone support is active.`

So, I changed from naive datatime `"2017-01-02 00:00:00"` to timezone aware datetime: `"2017-01-02 00:00:00Z"`. `Z` ([from "Zulu"](https://stackoverflow.com/questions/9706688/what-does-the-z-mean-in-unix-timestamp-120314170138z)) in the end means UTC, this is the timezone of my Django project (`TIME_ZONE = 'UTC'` in `settings.py`). [This](https://docs.djangoproject.com/en/1.11/topics/i18n/timezones/#code) is a good read from Django docs about time zones.

But then, I was getting an error from DjangoQL:

```
(...)
File "/usr/local/lib/python3.5/dist-packages/djangoql/schema.py", line 215, in validate
    repr(value),
djangoql.exceptions.DjangoQLSchemaError: Field "datetime_created" can be compared to timestamps in "YYYY-MM-DD HH:MM" format, but not to '2017-01-01T00:00Z'
```

Essentially, `validate` in DjangoQL's `DateTimeField` doesn't allow adding this `Z` in the end.

I ended up copy-pasting it and tweaking slightly, so that it allows this `Z`:

```python
class UTCDateTimeField(DateTimeField):
    name = 'datetime_created'
    value_types_description = 'timestamps in "YYYY-MM-DD[ HH:MM[:SS[Z]]" format'

    def validate(self, value):
        super(DateTimeField, self).validate(value)
        mask = '%Y-%m-%d'
        if len(value) > 10:
            mask += ' %H:%M'
        if len(value) > 16:
            mask += ':%S'
        if len(value) > 19:
            mask += 'Z'
        try:
            datetime.datetime.strptime(value, mask)
        except ValueError:
            raise DjangoQLSchemaError(
                'Field "%s" can be compared to timestamps in '
                '"YYYY-MM-DD[ HH:MM[:SS[Z]]" format, but not to %s' % (
                    self.name,
                    repr(value),
                )
            )
```

Using such custom field works, no warnings.

I thought I will post here for 3 reasons:
1. People with the same problem can get a hand.
2. Maybe a pull request to DjangoQL can be created to improve DateTimeField.
3. Maybe there is a different way of doing it?

Bonus question: I'm missing TimeField, to be able to filter by `"HH:MM[:SS]"` only (for example, to get meals from `12:00` o'clock... tea etc.), should I also use custom field?

**Comment by stebunovd** [comment]
thanks, good catch about timezone! Actually, this is not just about warnings. That behavior could result in weird situations when timezone is different between a database and Django settings, so I made a fix which sets timezone explicitly for both DateField and DateTimeField. Please check v0.8.6

as for TimeField - yeah, I suppose custom field would be a reasonable way to go

**Comment by AdamStelmaszczyk** [comment]
Thanks, that looks great, now I can just have nice `"2017-01-02"` in my test (and DjangoQL will correctly set the timezone).

However, one test in my project that was passing before is now failing with `AssertionError: 3 != 0`:

```python
http_status, response_json = self._get(
    '/users/user_1/meals/',
    {'filter': 'datetime_created ~ "2017-01-01"'},
)
assert_equal(3, response_json['count'])
```

I didn't know how to write "from a given day" on the first place (`datetime_created = "2017-01-01"` is not equivalent, it gets items from one second `"2017-01-01 00:00:00"`). 

I found out that `datetime_created ~ "2017-01-01"` worked. However it stopped working with 0.8.6.

Any advice?

**Comment by stebunovd** [comment]
interesting. I never thought about LIKE comparisons for datetime fields, so it was supported basically by accident :) However, this is an obviously useful case, so I added explicit support for it as well. Your case should be working back with v0.8.8 (please let me know if it doesn't)

**Comment by AdamStelmaszczyk** [comment]
Works like a charm, thank you.
