### ISSUE TITLE
Revert to Django builtin search?

### ISSUE THREAD

**Issue by ciarancourtney** [ivelum/djangoql#16]
Hi,

Is it currently a feature to switch between django (simple) and djangoql (advanced) search? Making an invalid search of `?q=foo` just gives `Unexpected end of input`, maybe if a query is invalid, assume its a simple search?

**Comment by stebunovd** [comment]
Hi,

I'm not sure if such behavior would be desirable for all users since it adds a kind of ambiguity. It can be challenging to reliably determine if a user has really made a mistake in a complex query, or did it just tried to perform a "simple" search instead. However, you can implement any custom logic for your application by overriding ``.get_search_results()`` method, like in #10.

does it make sense?

**Comment by ciarancourtney** [comment]
Thanks @stebunovd I'll look into that

**Comment by ciarancourtney** [comment]
Hi @stebunovd I've tested an implementation that tries a tentative DjangoQL search and catches exception, then based on that it continues search using simple or DjangoQL. Any feedback or possible future API changes that might break this?

    from django.contrib import admin

    from djangoql.admin import DjangoQLSearchMixin
    from djangoql.exceptions import DjangoQLError
    from djangoql.queryset import apply_search

    class DjangoQLMixin(DjangoQLSearchMixin, admin.ModelAdmin):

        def get_search_results(self, request, queryset, search_term):
            use_distinct = False
            if search_term:
                try:
                     queryset = apply_search(queryset, search_term, self.djangoql_schema)
                except DjangoQLError:
                    queryset, use_distinct = admin.ModelAdmin.get_search_results(self, request, queryset, search_term)
                else:
                    queryset, use_distinct = DjangoQLSearchMixin.get_search_results(self, request, queryset, search_term)

            return queryset, use_distinct

**Comment by stebunovd** [comment]
looks good to me. If it works for your business case, it should be fine. As for the future API changes, I cannot provide 100% guarantee, this software hasn't reached 1.0 yet. So in theory, there could be changes. However, I don't plan any changes that might affect this right now

**Comment by stebunovd** [comment]
This is now supported in v0.10.0, see [Using together with a standard Django admin search](https://github.com/ivelum/djangoql#using-together-with-a-standard-django-admin-search).
