### ISSUE TITLE
Support for groups using parentheses

### ISSUE THREAD

**Issue by Nekmo** [ivelum/djangoql#38]
Hi! We need to make some slightly complicated queries in our project that require parentheses. For example:

```
(a and b) or (b and c)
```

I do not know how complicated it would be to support this feature.

Thanks :)

**Comment by stebunovd** [comment]
Hi @Nekmo,

DjangoQL already supports parentheses. If you have a problem with a particular query - please feel free to post it here.


thanks,

Denis
