### ISSUE TITLE
DjangoQL as deafult search option in Django Admin even when search_fields is set

### ISSUE THREAD

**Issue by nicolazilio** [ivelum/djangoql#42]
At the moment, as stated in the docs "If you define `search_fields` in a ModelAdmin class, DjangoQL integration would automatically recognize this and let users choose between a standard Django search (that you specified with search_fields) and Advanced Search with DjangoQL". 

The issue that, under these circumstances, the standard Django search option is shown as default. If I want to use DjangoQL, I need to manually turn it on. I would prefer the opposite, whereby DjangoQL is chosen as the default search option.

I have no choice but to include `search_fields` in my ModelAdmin, although I don't really care for it, because I've implemented some autocomplete fields using Django's 2.0 `autocomplete_fields`, which require `search_fields` to be set, as described [here](https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields).

What would be the easiest way to set DjangoQL as the main deafult search option in the change_list view even when `search_fields` is set?

**Comment by iceone** [comment]
Hi @nicolazilio! 
I think the best option will be to implement a special class property in the `DjangoQLSearchMixin` which will control the initial DjangoQL search toggle state.

I hope we can implement it soon.

Thanks,
Ilnur

**Comment by nicolazilio** [comment]
Thanks, I will try that out!

**Comment by stebunovd** [comment]
thanks @nicolazilio ! 

this is now implemented as a standard feature, and the checkbox is now on by default. If for any reason you'd like to turn it off, there's ``djangoql_completion_enabled_by_default`` parameter that controls that, see [in the docs](https://github.com/ivelum/djangoql#using-djangoql-with-the-standard-django-admin-search).
