### ISSUE TITLE
case insensitive search

### ISSUE THREAD

**Issue by caleb15** [ivelum/djangoql#44]
It would be nice if the search was case insensitive by default. I keep on accidentally using the wrong case. I might be able to get company open source time to submit a PR for this but probably not anytime soon.

**Comment by stebunovd** [comment]
hey @caleb15,

The `~` comparison operator translates into `__icontains`, that means case-insensitive comparison with SQL `like` operator. Direct strings comparison via `=` should be case-sensitive or case-insensitive depending on your database collation settings. Just in case if you're using SQLite - please note that [SQLite is unable to do a case-insensitive comparison of Unicode strings](https://www.sqlite.org/faq.html#q18) at all.


thanks,

Denis

**Comment by caleb15** [comment]
Ah, I tested it and you're right, ~ is case-insensitive. Thanks for the tip.

We are not using SQLlite, but that's good to know.

**Comment by pandichef** [comment]
Which database would be case sensitive for `=`?  I'm using MySQL and it's case insensitive for both `~` and `=`... which I don't love.  For future development, I'd suggest going case insensitive everywhere and adding functions like lower(), upper(), startswith(), and endswith().  So if you prefer case insensitive, you can use `lower(county)~"germany"`.

**Comment by stebunovd** [comment]
> Which database would be case sensitive for =? 

it depends on the collation for a particular column in a table. Database engines have different collations, both case-sensitive and case-insensitive, that can be set on different levels (database, table, or column). Here is the [explanation for MySQL](http://www.mysqltutorial.org/mysql-collation/).

DjangoQL `=` operator is translated to a direct comparison in Django ORM, i.e. `name = "John"` on User model becomes `User.objects.filter(name="John")`. The latter is translated to an SQL query like `select * from auth_user where name = "John"`, and the database engine itself performs string comparisons that are case-sensitive or case-insensitive depending on the collation for `name` column in `auth_user` table.

In theory, Django provides an abstraction over this in the form of `__exact` and `__iexact` comparison operators, but unfortunately [it doesn't work for MySQL](https://code.djangoproject.com/ticket/2170).
