### ISSUE TITLE
Multiple model filtering

### ISSUE THREAD

**Issue by nabobalis** [ivelum/djangoql#45]
I am not sure if this is a feature request or just my lack of understanding about this package.

But I wanted to create a page that would allow me to filter across two or more models. 
For example, for table A I want to check one field is true and then reference another (linked) table to make sure another field has a certain value.

**Comment by vkrizan** [comment]
I believe that this is currently not possible, unless the another table is has a relationship to the primary table.  The QL works with one query(set), the same way as if you'd write `DjangoModel.objects.filter(...)`, but it does not have a support to create a subquery (e.g. `FirstModel.objects.filter(field__in=OtherModel.objects.all())`.

**Comment by nabobalis** [comment]
Thanks, so just to clarify it might work if the other tables were linked by a Foreign Key?

**Comment by vkrizan** [comment]
Yes, ForeignKey would work. Just like within a QuerySet: `child_table__otherfield`.
