### ISSUE TITLE
Allow non-quoted strings as right hand values

### ISSUE THREAD

**Issue by holvianssi** [ivelum/djangoql#5]
I'm wondering if it would be somehow possible to allow non-quoted strings as right hand values for single word searches. With this you could do queries like `name ~ anssi` or `phone = 0505968123`. Strings with spaces would of course need to be quoted, so `name = "Anssi Kääriäinen"` would be the search for full name.

I know this leads to some complications, like case `name = None` (could be said that name = "" should match both name is none and name is empty string cases) and maybe some complications I don't even know in the lexer and parser parts. On the other hand I believe users would prefer the ability to do simple searches without quoting.

**Comment by stebunovd** [comment]
yeah that's a difficult tradeoff. 

I also think that this feature could make the language more user-friendly, especially for non-experienced users. Such behavior is supported in JIRA Query Language (JQL) for example.

At the same time there're downsides too. You already mentioned first one - we'll irreversibly loose ability to explicitly compare strings to None. Using empty string "" to compare to both None and empty strings may work for many cases, and may even make the life simpler for those cases. However this approach is implicit and I can imagine another cases when explicit comparison to None could be helpful.

One more complication that I can think about is related to possible new language features. For example, right now we don't have support for F-expressions, that would allow to compare database fields to each other. If ever we'd like to introduce such feature, that would effectively mean that field names could be located on both sides of comparison operator, like ``username = email``. In this example optional quotes would create a problem for the parser - it can't reliably tell if ``email`` is a field or a string in this context.

That said, I'm open to any thoughts and ideas on this one. Maybe I'm missing something, or maybe this feature is more important for end users than comparisons to None or extra language features... I'm not sure yet. Maybe we should collect more feedback

**Comment by holvianssi** [comment]
I think what could be done here is making the grammar accept non-quoted strings on the right hand side, but make the fields do the validation. This way, BooleanField would check that the value would be either True or False or None. If it's not one of those, then it would show an error saying only True, False and None are allowed values. Similarly, StrField would check that the right hand value is a quoted string. This would be the default, but you could create a NonQuotedStrField which doesn't check for quotes, and allows for searches like `email = akaariai@gmail.com`.

The method itself could be something like `ui_to_orm(value)`. It would then either return an F-object, or a value used for the comparison in the ORM. For choice fields, this would allow using display values in the UI, but query based on the value saved to DB. So, if you have a choice of ('paid', 'Paid') for some field, then ui_to_orm() would return 'paid' for user input 'Paid'.

A possible approach for the references (and maybe even None) would be to require some special character for this style of queries. Say username = $email or username = $None. Now you have a conflict for $email as search query and $email as field reference, but then just use quoting for the first one.

I believe moving the value validation to field level allows for greater flexibility, better error messages and more features. So, my vote for making the grammar as allowing as possible, but still keeping the field level validation strict.

**Comment by stebunovd** [comment]
Validation is already performed on fields level since version 0.8.0, we check value types compatibility there. However detection of constant values vs. names is performed earlier, this is on language grammar level at the moment. Moving this to fields or schema level would make it context-dependent, and actually I'm not sure if it's a good idea..

As for special characters - I don't see yet how it could help to resolve this. What if user really wants to search for ``username = $email`` where $email is supposed to be a string? Fallback to quotes would work of course, but it would work even without $ symbol, too.

I wonder if we could make quotes problem less painful with alternate approach - making auto-completion smarter. If it could do a better job at reminding users that strings should be quoted, and auto-completing quotes in cases when users forget them, probably this could work as well. And it would allow us to keep the language grammar explicit and context-independent.

**Comment by holvianssi** [comment]
Yep, if everything on the right hand side is just a value, it means it's harder to do autocompletion and hints in the UI. Supplying a regex and a help string from the field to javascript would allow javascript to both check the value and to also offer some help in case the value isn't acceptable for the field.

For the username = $email case, the idea is that searches against strings with $ in the beginning aren't common, so users wouldn't need to quote the strings often.

All in all, keeping the quotes there for now seems like a good option. If there is feedback from users that they find the current search style hard to use, then you have the option to go for no-quotes solution. So, worst case scenario for the current approach is that you need to change something later...

So, I'll close this one. Thanks for the discussion!
