### ISSUE TITLE
Add "Syntax Help" link to the error messages that get populate

### ISSUE THREAD

**Issue by AngellusMortis** [ivelum/djangoql#50]
Another "nice to have" from others that have been using DjangoQL.

Error messages are rather cryptic to new users and users can very easily miss the "Syntax Help" link in the auto-complete. It would be great if it was also in the error messages that also get created at the top of the page.

**Comment by stebunovd** [comment]
thanks @AngellusMortis, this is a great idea. Please check v0.13.0 with this improvement added
