### ISSUE TITLE
Small improvement in docs regarding customizing fields

### ISSUE THREAD

**Issue by joeydebreuk** [ivelum/djangoql#55]
In my situation I had a model containing a `created` datetime field, which I wanted to customize to search on date only. I got confused because the equivalent of the example code pasted below didn't seem to work.

```
class UserDateJoinedYear(IntField):
    name = 'date_joined_year'

    def get_lookup_name(self):
        return 'date_joined__year'


class UserQLSchema(DjangoQLSchema):
    def get_fields(self, model):
        fields = super(UserQLSchema, self).get_fields(model)
        if model == User:
            fields = [UserDateJoinedYear()] + fields
        return fields
```
It turned out it didn't work because in order to overwrite a field name that already exists, I needed to change the line:
`fields = [UserDateJoinedYear()] + fields`
to:
`fields = fields + [UserDateJoinedYear()]`

Makes perfect sense it works this way. Maybe you should make the same change in your example to avoid confusion.

**Comment by stebunovd** [comment]
thanks @joeydebreuk !
