### ISSUE TITLE
using "in" with an Integer field

### ISSUE THREAD

**Issue by pandichef** [ivelum/djangoql#58]
I have a PositiveSmallIntegerField with choices specified.  The choices are specified as a subclass of `django.db.models.IntegerChoices`, which I believe is new in Django 3.0.

`my_field=1 or my_field=2` works fine.  However, `my_field in (1,2)` returns an empty `QuerySet`.  Has anyone else encountered this?

**Comment by stebunovd** [comment]
hey @pandichef, thank you for reporting this! That was an inconsistency in handling fields with choices, which is now fixed in v0.14.1
