### ISSUE TITLE
Airquote disappears 

### ISSUE THREAD

**Issue by nicolazilio** [ivelum/djangoql#62]
djangoql 0.14.1

Hello,

After upgrading to version 0.14.1 and updating my code so that get_options() takes the new search parameter, I have experienced an odd behaviour. I am not entirely sure whether this is a bug with djangoql or something that I did wrong.

When I select my choice from a list of string options, the second airquote disappears, which causes an error when I hit the search button

<img src="https://user-images.githubusercontent.com/2800360/101137766-9bba0180-360f-11eb-89cc-008366400758.png" width="300">

<img src="https://user-images.githubusercontent.com/2800360/101137798-ab394a80-360f-11eb-9c00-7a0f009efdcc.png" width="300">

This is the underlying code

```
class SearchFieldOptSupplier(StrField):

    model = Order
    name = 'supplier'
    suggest_options = True

    def get_options(self, search):

        if len(search) < 3:
            return ["Type 3 or more characters to see suggestions"]
        else:
            return self.model.objects.filter(supplier__icontains=search).\
                        distinct()[:10].values_list(self.name, flat=True)
```

The strange thing is that I have other similar classes that do NOT show the same problem, such as the following

```
class SearchFieldOptCostUnit(StrField):

    model = CostUnit
    name = 'cost_unit'
    suggest_options = True

    def get_options(self, search):
        return self.model.objects.filter(name__icontains=search).order_by('name').\
        values_list('name', flat=True)
```

Any ideas?

**Comment by stebunovd** [comment]
hey @nicolazilio, I can confirm that this is a bug in the DjangoQL widget and not a problem with your code. I've replicated it locally on my machine. I plan to release the fix soon in v0.14.3. Thank you for reporting this!

**Comment by stebunovd** [comment]
v0.14.3 with the bug fix is on PyPI - please check it out!

**Comment by nicolazilio** [comment]
Awesome, now it works, thanks a lot!
