### ISSUE TITLE
Can I change once search with another?

### ISSUE THREAD

**Issue by instasck** [ivelum/djangoql#70]
I need to replace user search for "chars" into an "id"
replacing:
qs1.filter(~Q(language__code_name='ar'))
with:
lang_id = Language.objects.filter(code_name='ar').first().id
qs1.filter(~Q(language__id=lang_id))

It fetching results much quicker for me (avoiding nested loops).
was not sure what to change.

Thanks for the awsome project.

**Comment by stebunovd** [comment]
Hey @instasck, thanks for using DjangoQL. 

You can modify any queries generated by DjangoQL by supplying your custom schema with field classes that override `.get_lookup_name()` and/or `.get_lookup_value()` methods for light customizations, or `.get_lookup()` method for fully-custom search implementation. 

Please find examples in the [Custom search fields](https://github.com/ivelum/djangoql#custom-search-fields) section of the readme. You might also want to check the original [.get_lookup()](https://github.com/ivelum/djangoql/blob/c4eaed892dd237e880bb40d37970645bfe980391/djangoql/schema.py#L115-L138) method implementation to see how it works - it's pretty simple actually.

**Comment by instasck** [comment]
Tell me what am I doing wrong:
This is the search a user do:
![image](https://user-images.githubusercontent.com/43851500/115680383-2ea7ce00-a35c-11eb-9b4d-29dbf5257d19.png)

I want it to switch to:
language.id != 2
![image](https://user-images.githubusercontent.com/43851500/115680641-6b73c500-a35c-11eb-9e7a-ebd480ee14e1.png)


I added this code:
''''
class FollowerLangField(IntField):
    name = 'language_code_name'

    def get_lookup_name(self):
        return 'language_id'

    def get_lookup_value(self, value):
        lang_id = Language.objects.filter(code_name=self.value).first().id
        return lang_id


class FollowerQLSchema(DjangoQLSchema):
    def get_fields(self, model):
        fields = super(FollowerQLSchema, self).get_fields(model)
        if model == Follower:
            fields += [FollowerLangField()]

        return fields


# Custom Admin for Follower model
class FollowerAdmin(DjangoQLSearchMixin, NumericFilterModelAdmin, SpecialActions):

    djangoql_schema = FollowerQLSchema
''''

**Comment by stebunovd** [comment]
> MANAGED TO DO IT !!! 

cool, I'm glad you figured it out :)
