### ISSUE TITLE
Search does not work with GenericIPAddress fields

### ISSUE THREAD

**Issue by HannaShalamitskaya** [ivelum/djangoql#76]
Unfortunately, for now, djangoql doesn't work with GenericIPAddress fields.

I am getting an exception:
"Field "field_name" has "unknown" type. It can be compared to , but not to '10.45.26.93'"

**Comment by stebunovd** [comment]
hey @HannaShalamitskaya, thank you for reporting this issue. It has been resolved in v0.15.0 which is now live on PyPI - please check it out!

**Comment by HannaShalamitskaya** [comment]
@stebunovd, thank you very much!

Everything works fine now
