### ISSUE TITLE
AttributeError: 'QuerySet' object has no attribute 'explain'

### ISSUE THREAD

**Issue by derekenos** [ivelum/djangoql#79]
I ran into the error:

```
File "/.../lib/python3.5/site-packages/djangoql/admin.py", line 87, in get_search_results
    qs.explain()
AttributeError: 'QuerySet' object has no attribute 'explain'
```

using Django 2.0.8
```
$ python -c 'import django; print(django.__version__)'
2.0.8
```

It looks like `QuerySet.explain()` was [added in `2.1`](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#explain)

I regrettably can't offer a different solution to the problem that [the usage of `explain` solves](https://github.com/ivelum/djangoql/blob/master/djangoql/admin.py#L84-L87). 

Thank you for this great project!

**Comment by stebunovd** [comment]
hey @derekenos, thank you for reporting the issue. The new version 0.15.2 with the fix is already on PyPI, please check it out.

**Comment by derekenos** [comment]
v0.15.2 resolves the issue. Thank you!
