### ISSUE TITLE
Abnormal scroll behavior for a long autocomplete list. 

### ISSUE THREAD

**Issue by zadoev** [ivelum/djangoql#8]
I failed to use scroll in  autocomplete dropdown box for a large sets of data. Here some details:

1. Sometimes mouse cursor starts to be tied with scrollbar. (Usually after drag and drop in scrollbar)
2. I'm also failed to use arrow down key. When you press it on latest visible element it scrolls to top and selection also jumps to any value from top. 
3. Mouse scroll works in the same way like arrow down key.

**Comment by stebunovd** [comment]
thank you for reporting this!

could you please provide more details - what is a "large" dataset? How many items it should contain for the problem to appear? Which browser are you using?

**Comment by zadoev** [comment]
Dataset: 203 items. 

OS: Mac OS X 10.12.3 64-bit
Browsers: 
Opera 42 and 44. 
Google Chrome 57

OS: Ubuntu 14.04:
Browsers:
Google chrome 56

**Comment by stebunovd** [comment]
fixed in v0.8.2
