### ISSUE TITLE
Support of Django 4.0

### ISSUE THREAD

**Issue by Lotfull** [ivelum/djangoql#86]
Hello,

Would it be possible to support this package for Django 4 version?

Here is the imports error that happening because in Django 4.0 `from django.conf.urls import re_path` was deprecated and [new usage](https://docs.djangoproject.com/en/4.0/ref/urls/#re-path) is `from django.urls import re_path`:
```
try:
    from django.conf.urls import re_path
except ImportError:  # Django <2.0
    from django.conf.urls import url as re_path
```

Exception:
```
File "python3.10/site-packages/djangoql/admin.py", line 28, in <module>
from django.conf.urls import url as re_path
ImportError: cannot import name 'url' from 'django.conf.urls'
```

Maybe some more exceptions happening, but this one is obvious. 

So can we add support of Django 4.0?

**Comment by stebunovd** [comment]
hey @Lotfull, thank you for the PR!

v0.17.0 with Django 4.0 support is already on PyPI, please check it out

**Comment by Lotfull** [comment]
Thank you, @stebunovd!
