### ISSUE TITLE
Collectstatic on Django 4 fails due to missing map file

### ISSUE THREAD

**Issue by magdapoppins** [ivelum/djangoql#89]
Trying to use whitenoise's collectfiles fails with

```
The JS file 'djangoql/js/completion.js' references a file which could not be found:
djangoql/js/completion.js.map
```
since the djangoql package apparently doesn't ship the .map file. Django 4 changed file discovery to also find sourcemap files, see e.g. https://code.djangoproject.com/ticket/33353. 

Could 
* the .map file be shipped with the package or 
* the sourcemap reference comment `//# sourceMappingURL=completion.js.map` be removed?

**Comment by stebunovd** [comment]
hey @magdapoppins, thank you for the PR!

v0.17.1 with the fix is already on PyPI, please check it out
